src/chsrc.c
👋 I got a homebrew-core PR to include the project, but I am bit confused with the license, so this is the update, also update to use spdx id, https://spdx.org/licenses/ (GPL-3.0 is deprecated). Let me know what you think.
relates to https://github.com/Homebrew/homebrew-core/pull/173951
=> chore(license): update to use spdx id

README.md
=> chore(docs): add `packaging status`

README.md, include/source.h, src/chsrc.c
=> Add os armbian

include/chsrc.h
在函数`chsrc_get_cpuarch()`中，查看cpu命令应该是`uname -m`?
https://github.com/RubyMetric/chsrc/blob/aa7ec3fb82583aa88a407859d4784a0aa98eec1c/include/chsrc.h#L753
`chsrc_prepend_to_file()`函数似乎忘记了添加空格导致sed命令缺少文件参数，
应为`xy_strjoin (4, "sed -i '1i ", str, "' ", file);`
https://github.com/RubyMetric/chsrc/blob/aa7ec3fb82583aa88a407859d4784a0aa98eec1c/include/chsrc.h#L683
=> fix problem in chsrc_get_cpuarch() and chsrc_prepend_to_file()

src/recipe/lang/Node.js.c
This pr is opened because an outdated command for changing Yarn's registry was reported by me with clues and detailed external references.
[GitHub #53]
=> Add contributor

README.md, pkg/README.md, src/chsrc.c
=> add AUR support documents

src/recipe/lang/Node.js/Bun.c
全局配置应该是 ~/.bunfig.toml 文件，
项目级配置应该是在 项目根目录的 bunfig.toml 文件。
~/.bun/bunfig.toml是无效的路径。
=> fix bunfig.toml path

src/chsrc-main.c, src/recipe/os/YUM/Fedora-Linux.c
- 不再支持fedora 38及以下版本
- 默认使用metalink匹配最快源, 提示用户可自行注释
=>     Fix Fedora

tool/download-release.sh
`curl -s https://raw.githubusercontent.com/RubyMetric/chsrc/refs/heads/main/tool/download-release.sh | sudo bash`
`curl -s https://raw.githubusercontent.com/RubyMetric/chsrc/refs/heads/main/tool/download-release.sh | sudo bash -s -- -d ./test`
如果此前已经下载`chsrc`，运行该命令会在原有安装路径覆盖旧版本
=> 添加linux，macos下载脚本

tool/install.ps1
1. Add new feature to install.ps1.: use `-h` for help, `-d` for specifying directory, `-v` for specifying `chsrc` version.
2. Help output: use `-h` to display `help`.
3. Specify directory: default dir is `${HOME}\Downloads`,  can use `-d <dir>` to specify the download directory.
4. Specify chsrc version: default version is `pre`, use `-v <version>` to specify.
5. Rewrite the whole file, rebuild its structure.
6. Use English Output: to avoid scrambled code.
Fixed #98 
Now can use `install.ps1` on windows to download **any version** of chsrc in **any directory**.
I've already test the `-h`, `-v`, `-d` flag on my machine. `OS Version: Windows 10 Professional 64-bit`, `CPU Model: 12th Gen Intel(R) Core(TM) i7-12700H`.
=> Rewrite pwsh script

src/recipe/ware/Docker-Hub.c
- 换源前检查root权限
- 使用`jq`将新增源添加到源列表首位, 会检查是否重复
- 不存在`jq`时使用`sed`替换`"registry-mirrors":[xxx]`中内容
=> feat: 自动化linux上docker换源过程

src/chsrc-framework.h
=> fix: 修复在非win系统上会产生nul文件的问题

src/recipe/lang/Rust/rustup.c, src/recipe/os/APT/Armbian.c, src/recipe/os/APT/Debian.c, src/recipe/os/APT/Kali-Linux.c, src/recipe/os/APT/Linux-Lite.c, src/recipe/os/APT/Raspberry-Pi-OS.c, src/recipe/os/APT/deepin.c, src/recipe/os/Alpine-Linux.c, src/recipe/os/OpenWrt.c, src/recipe/os/Void-Linux.c, src/recipe/os/YUM/AlmaLinux.c, src/recipe/os/YUM/openEuler.c, src/recipe/ware/Anaconda.c
Add upstream for `rustup`, `Armbian`, `Debian`, `Kali`, `Linux Lite`, `Raspberry Pi`, `deepin`, `Alpine`, `OpenWrt`, `Void Linux`, `AlmaLinux`, `openEuler` and `Anaconda`
=> Add some upstreams

src/recipe/os/APT/ROS.c
=> Fix ROS Error

Makefile
使用 `clang` 编译项目失败
`Makefile` 中 `clang` 在指定编译目标时使用的参数 `-Target` 错误，应为 `-target`
改过来就好了，虽然后面的 `echo; echo` 在 Windows 上无法执行，但不影响编译
=> Fix incorrect clang target parameter

src/chsrc-main.c, src/recipe/lang/Python/Python.c, src/recipe/lang/Python/common.h, src/recipe/lang/Python/uv.c, src/recipe/menu.c
- 实现了 `uv`的换源 #139 
- 将 `uv`添加进 `Python group`, 在 `chsrc set python`时一起换源
=> Support `uv` for Python

src/recipe/os/APT/common.h, src/recipe/os/YUM/Rocky-Linux.c
- 修复`Rocky`版本检测失败, 去除版本号外的 "" #149 
- 使用上述方式检测 `Debian` 系版本号
=> Fix `Debian`, `Rocky` version detection

src/recipe/os/OpenWrt.c
- #153 openwrt 换源异常
- openwrt reset 有实现但没定义
<br>
- 修改 openwrt 源时不能漏掉 `/releases`
- 补上openwrt reset 的定义
=> Dev 修复 `openwrt`的 getsrc 和 resetsrc

README.md, lib/xy.h, src/chsrc-main.c
Fix README and segmentation fault for FreeBSD, addressing #163
All credits to @ccmywish
- Closes #163
修改README，增加-Ilib；修复xy_run()
```c
static char *
xy_run (const char *cmd, unsigned long n)
{
// 少了一个 return
xy_run_iter (cmd, n, NULL);
}
```
---
如上
---
如上
---
```bash
./chsrc set freebsd first
```
=> Fix README and segmentation fault for FreeBSD, addressing #163

src/recipe/os/APT/Linux-Mint.c
- 当前实现中 `Linux Mint`换源存在问题
- Close #167 
-  修复了`Linux Mint`换源
---
- 修改了用于换源的 sed命令
- 运行 chsrc set mint
=> fix `mint` setsrc

src/chsrc-main.c, src/framework/mirror.c, src/recipe/ware/Flathub.c
- 近期`Flathub`上海交通大学镜像站存在不兼容的问题
- #178 
- 修复了`Ware Flathub`换源
- 在`mirror.c`中区分了上海交通大学思源镜像站和致远镜像站
- 添加Flathub官方仓库
- 添加了`Flathub.c`中用于测试的`MirrorSite_t`和对应的测试链接
- 运行 chsrc set flathub
=> Fix `flathub` chsrc

.github/workflows/pkg-aur-git.yml, .github/workflows/pkg-aur-rel.yml
#177 `chsrc-bin` 未正常发布但没有报错。
经排查，是由于上游Action `KSXGitHub/github-actions-deploy-aur@3.0.1` 在`pkgbuild`参数对应的文件名不是默认的`PKGBUILD`时（此处为`./PKGBUILD_bin`），不会使用提供的文件替换目标仓库中的`PKGBUILD` [ref](https://github.com/KSXGitHub/github-actions-deploy-aur/issues/44) 。这一问题导致了发布更新时始终错误地使用了旧版本的`PKGBUILD`文件，并且没有错误提示。
- 解决： #177 
- 上游问题： https://github.com/KSXGitHub/github-actions-deploy-aur/issues/44
- 上游已修复： https://github.com/KSXGitHub/github-actions-deploy-aur/pull/45
更新使用的上游Action至 `KSXGitHub/github-actions-deploy-aur@4.1.1`。
=> fix #177: fails without error when publishing chsrc-bin to AUR

tool/installer.sh
bash脚本在0.x.y类型的版本中无法正确构造URL，缺少前缀v。在URL中正确的版本字符串类型应该是"v0.x.y"
Related to #176 
添加了前缀变量version_prefix，并添加了如果版本号形似0.x.y，则在构造URL的时候添加version_prefix前缀
---
此bash安装器没有经过充分的黑盒测试，可能在不同的版本/系统上还存在问题，并且如果版本号` < 0.1.4`，正则表达式`0\.([1-9])\.([0-9]`仍可检测通过，此处是否需要fix？
---
我在本地提取了此段改动代码进行简单测试，并成功通过。
---
=> Fix: upgrade bash installer

src/recipe/lang/Python/uv.c
当前 `chsrc set uv` 命令存在两个问题
- 当 uv.toml 不存在时，`chsrc set uv` 向该文件写入了错误的内容
```toml
-e [[index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
```
- 当 uv.toml 存在时，由于命令执行错误导致 `chsrc set uv` 本意修改 [[index]] 当前的 url，实际上会添加了一个新的 [[index]]
```toml
-e [[index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
-e [[index]]
url = "https://mirrors.pku.edu.cn/pypi/web/simple"
default = true
```
N/A
修复了上述两个问题，在更新 ~/.config/uv/uv.toml 时避免错误写 or 重复写
- 使用 `printf` 命令代替 `echo -e` 避免向文件中写入 '-e'
- 修改错误的 `sed` 命令避免向文件中写入冗余的 '[[index]]'
- 运行 `chsrc set uv xxx` 验证 uv.toml 是否正确更新
=> fix config error in `uv.toml`

src/chsrc-main.c, src/recipe/lang/Python/uv.c
当不存在 `uv.toml` 时，执行 `chsrc set uv xxx` 可以成功进行换源但是会报错：`grep: /path/to/uv.toml: No such file or directory`
#188 
修复了 `uv.toml` 不存在时输出不必要的错误提示的问题
- 当 `uv.toml` 不存在时直接写入新文件
- 当 `uv.toml` 存在时执行原有逻辑：如果 [[index]] 不存在则追加，否则替换 url
运行以下示例不会输出 `No such file or directory`
```sh
rm /path/to/uv.toml
chsrc set uv xxx
```
=> remove useless error messages when `uv` is set but no config file exists

src/chsrc-main.c, src/recipe/lang/Dart/Flutter.c, src/recipe/lang/Dart/Pub.c, src/recipe/lang/Dart/common.h, src/recipe/menu.c
- Windows 下 Flutter 换源方法错误
- Closes https://github.com/RubyMetric/chsrc/issues/192
- 使用 `setx` 命令设置用户变量
- 增加 CUFG (China Flutter User Group)
- 增加 默认源测速
---
- 使用 `setx` 命令设置用户变量
---
- 使用 `setx` 命令设置用户变量
- 增加 CUFG (China Flutter User Group)
- 增加 默认源测速
---
- 不太懂 C 和本项目的协作流程，如果有问题请多多指教
---
```powershell
D:\temp\chsrc [flutter ≡]> ucrt64 -c "make CC=gcc"
Compile done using 'gcc' -Iinclude -Ilib
D:\temp\chsrc [flutter ≡]> clang64 -c "make CC=clang"
Compile done using 'clang' -Iinclude -Ilib -target x86_64-pc-windows-gnu
D:\temp\chsrc [flutter ≡]> .\chsrc.exe set flutter
[chsrc 测速] 测速中
^ 上游默认源 (https://storage.googleapis.com) ... 23.26 MByte/s
- China Flutter User Group ... 12.14 MByte/s
- 上海交通大学致远镜像站 ... 46.73 MByte/s
- 清华大学开源软件镜像站 ... 42.01 MByte/s
- 南京大学开源镜像站 ... 12.90 MByte/s
最快镜像站: …
```
=> Update Flutter recipe

src/framework/mirror.c, src/recipe/lang/Rust/Cargo.c, src/recipe/menu.c
重新启用 CQU 镜像站
在开发的时候由于 CQU 封杀策略过严（5次便封杀IP），所以出于保护用户体验的问题，我没有启用它，并且后续我们和其某位管理员有一次不愉快的经历。
但是此PR由用户提出，尊重用户的需求和体验，我们也不必再计较以往的事情。
- Relates #209
<br>
重新启用
<br>
=> Re-add `cqu` mirror

src/recipe/ware/TeX-Live.c
1. 尝试性地增加了tlmgr各镜像站的测速链接
2. `N/A`
<br>
选取了一个20M的package作为测速目标，手动下载测试无误
=> add tlmgr speed test url

.vscode/settings.json
1. 原来的设置没搞好，在我的设备上还是会自动format，所以打了个补丁，现在应该可以适用于全部设备了
2. `N/A`
1. 增加了几种格式的format禁止设置
2. 重新排序了一下，现在观感好多了
3. 硬设置了tab为2（与现有文件一致）
=> reset settings to avoid auto-format

src/recipe/lang/Rust/rustup.c
1. 增加了rustup的测速链接，文件为20M
2. 更正了menu的一处描述，原来会提示如下
```powershell
PS D:\Temp\chsrc> chsrc set rustup USTC
chsrc: 镜像站 USTC 不存在
chsrc: 查看可使用源，请使用 chsrc list rust_rustup
PS D:\Temp\chsrc> chsrc list rust_rustup
chsrc: 暂不支持的换源目标。使用 chsrc list targets 查看所有支持的目标
PS D:\Temp\chsrc> chsrc list rustup     
指定使用某源，请使用 chsrc set rustup <code>
```
增加测速链接
=> add speed test

src/framework/core.c
1. fix #257 
<br>
换用 `command -v`，这玩意应该是都有的
=> 尝试修复which不存在的问题

lib/xy.h
1. 增加 `xy_str_find`
2. 增加 `xy_str_take_until_newline`
=> xy.h 增加str类的通用函数

src/framework/core.c
1. patch #294 
<br>
1. 修复了 ccmywish 提到的格式问题、无用的额外赋值问题等
2. 在 Windows 上使用 `GetTempPath` 和 `GetTempFileName` 创建临时文件（这也是winapi推荐的标准方式）并且这样的话理论上也可以大幅避免注入攻击或者临时文件存在等问题
3. 增加了一点错误处理，上次没考虑全，漏情况了
=> 修复 chsrc_make_tmpfile 在win上错误处理不完善的问题
